//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileShareServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acces
    {
        public int id_acces { get; set; }
        public int file_id { get; set; }
        public int user_id { get; set; }
    
        public virtual File File { get; set; }
    }
}
