//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileShareServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id_pers { get; set; }
        public string pers_name { get; set; }
        public string pers_surname { get; set; }
        public string pers_fath { get; set; }
        public int us_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
